import './globals.css'
import Script from 'next/script'

export const metadata = {
  title: 'p5.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.11.2/p5.min.js" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.11.2/addons/p5.sound.min.js" />
        <Script src="https://cdn.socket.io/4.5.4/socket.io.min.js" />
      </head>
      <body>{children}</body>
    </html>
  )
}